# Generated by Django 2.2.7 on 2020-01-30 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import submission.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0003_auto_20200130_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python')], default='C++', max_length=10)),
                ('verdict', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Wrong Answer'), (3, 'Compilation Error'), (4, 'Time Limit Exceeded'), (5, 'Memory Limit Exceeded'), (6, 'Run Time Error')], default=0)),
                ('time', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('memory', models.IntegerField(default=0)),
                ('code', models.FileField(upload_to=submission.models.path_to_save)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
