# Generated by Django 2.2.7 on 2020-01-30 13:49

import ckeditor_uploader.fields
from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('tags', models.IntegerField(blank=True, verbose_name=models.CharField(max_length=100))),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('sample_input', ckeditor_uploader.fields.RichTextUploadingField()),
                ('sample_output', ckeditor_uploader.fields.RichTextUploadingField()),
                ('time_limit', models.IntegerField(verbose_name=models.IntegerField(default=1))),
                ('memory_limit', models.IntegerField(default=256)),
                ('input_file', models.FileField(upload_to=problem.models.path_to_save)),
                ('output_file', models.FileField(upload_to=problem.models.path_to_save)),
                ('no_of_submissions', models.IntegerField(default=0)),
                ('no_of_accepted', models.IntegerField(default=0)),
            ],
        ),
    ]
