# Generated by Django 2.2.7 on 2020-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200130_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
